/*
# Criar modelo PostgreSQL de gestão operacional

1. Objetivo
- Converte o modelo lógico fornecido em um esquema PostgreSQL normalizado para funcionários, administradores, máquinas e produtos.
- Mantém os atributos apresentados nas imagens e transforma os relacionamentos N:N em tabelas de associação explícitas.

2. Novas tabelas e colunas
- `funcionarios`: `id_funcionario` (identidade e chave primária), `nome_funcionario`, `email_funcionario`, `cpf_funcionario` e `telefone_funcionario`.
- `administradores`: `id_administrador` (identidade e chave primária), `cpf_administrador`, `nome_administrador`, `email_administrador` e `telefone_administrador`.
- `maquinas`: `id_maquina` (identidade e chave primária), `funcionamento_maquina`, `tipo_maquina` e `nome_maquina`.
- `produtos`: `id_produto` (identidade e chave primária), `tipo_produto` e `nome_produto`.
- `gerencia_funcionario_maquina`: vínculo entre funcionário e máquina, com chave primária composta.
- `gerencia_funcionario_produto`: vínculo entre funcionário e produto, com chave primária composta.
- `gerencia_administrador_maquina`: vínculo entre administrador e máquina, com chave primária composta.
- `gerencia_administrador_produto`: vínculo entre administrador e produto, com chave primária composta.
- `gerencia_administrador_funcionario`: vínculo entre administrador e funcionário, com chave primária composta.

3. Integridade e qualidade dos dados
- Todas as identificações usam `GENERATED BY DEFAULT AS IDENTITY`.
- Campos descritivos obrigatórios aceitam até 255 caracteres e não podem ser vazios.
- CPF é único por tipo de pessoa e e-mail é único sem diferenciar maiúsculas de minúsculas.
- Relacionamentos usam chaves estrangeiras com `ON DELETE CASCADE` nas tabelas de associação, evitando vínculos órfãos.
- Índices são criados para as colunas estrangeiras e para as buscas por CPF e e-mail.

4. Segurança
- Row Level Security é habilitado em todas as nove tabelas.
- Como o modelo não inclui autenticação ou isolamento por usuário, as tabelas ficam disponíveis para os papéis `anon` e `authenticated`, permitindo CRUD para o aplicativo compartilhado.
- As políticas são separadas por operação: SELECT, INSERT, UPDATE e DELETE.

5. Observações importantes
- `Chave` do modelo original foi normalizada para `id_funcionario`, alinhando-a ao nome usado na segunda imagem.
- Os atributos textuais de funcionamento, tipo e nome foram preservados como texto limitado a 255 caracteres, sem inventar uma lista fechada de valores que não aparece no modelo.
*/

CREATE TABLE IF NOT EXISTS public.funcionarios (
  id_funcionario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_funcionario varchar(255) NOT NULL CHECK (btrim(nome_funcionario) <> ''),
  email_funcionario varchar(255) NOT NULL CHECK (btrim(email_funcionario) <> ''),
  cpf_funcionario varchar(14) NOT NULL CHECK (btrim(cpf_funcionario) <> ''),
  telefone_funcionario varchar(30) NOT NULL CHECK (btrim(telefone_funcionario) <> '')
);

CREATE TABLE IF NOT EXISTS public.administradores (
  id_administrador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpf_administrador varchar(14) NOT NULL CHECK (btrim(cpf_administrador) <> ''),
  nome_administrador varchar(255) NOT NULL CHECK (btrim(nome_administrador) <> ''),
  email_administrador varchar(255) NOT NULL CHECK (btrim(email_administrador) <> ''),
  telefone_administrador varchar(30) NOT NULL CHECK (btrim(telefone_administrador) <> '')
);

CREATE TABLE IF NOT EXISTS public.maquinas (
  id_maquina integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funcionamento_maquina varchar(255) NOT NULL CHECK (btrim(funcionamento_maquina) <> ''),
  tipo_maquina varchar(255) NOT NULL CHECK (btrim(tipo_maquina) <> ''),
  nome_maquina varchar(255) NOT NULL CHECK (btrim(nome_maquina) <> '')
);

CREATE TABLE IF NOT EXISTS public.produtos (
  id_produto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_produto varchar(255) NOT NULL CHECK (btrim(tipo_produto) <> ''),
  nome_produto varchar(255) NOT NULL CHECK (btrim(nome_produto) <> '')
);

CREATE TABLE IF NOT EXISTS public.gerencia_funcionario_maquina (
  id_funcionario integer NOT NULL REFERENCES public.funcionarios(id_funcionario) ON DELETE CASCADE,
  id_maquina integer NOT NULL REFERENCES public.maquinas(id_maquina) ON DELETE CASCADE,
  PRIMARY KEY (id_funcionario, id_maquina)
);

CREATE TABLE IF NOT EXISTS public.gerencia_funcionario_produto (
  id_funcionario integer NOT NULL REFERENCES public.funcionarios(id_funcionario) ON DELETE CASCADE,
  id_produto integer NOT NULL REFERENCES public.produtos(id_produto) ON DELETE CASCADE,
  PRIMARY KEY (id_funcionario, id_produto)
);

CREATE TABLE IF NOT EXISTS public.gerencia_administrador_maquina (
  id_administrador integer NOT NULL REFERENCES public.administradores(id_administrador) ON DELETE CASCADE,
  id_maquina integer NOT NULL REFERENCES public.maquinas(id_maquina) ON DELETE CASCADE,
  PRIMARY KEY (id_administrador, id_maquina)
);

CREATE TABLE IF NOT EXISTS public.gerencia_administrador_produto (
  id_administrador integer NOT NULL REFERENCES public.administradores(id_administrador) ON DELETE CASCADE,
  id_produto integer NOT NULL REFERENCES public.produtos(id_produto) ON DELETE CASCADE,
  PRIMARY KEY (id_administrador, id_produto)
);

CREATE TABLE IF NOT EXISTS public.gerencia_administrador_funcionario (
  id_administrador integer NOT NULL REFERENCES public.administradores(id_administrador) ON DELETE CASCADE,
  id_funcionario integer NOT NULL REFERENCES public.funcionarios(id_funcionario) ON DELETE CASCADE,
  PRIMARY KEY (id_administrador, id_funcionario)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_funcionarios_cpf ON public.funcionarios (cpf_funcionario);
CREATE UNIQUE INDEX IF NOT EXISTS uq_funcionarios_email_lower ON public.funcionarios (lower(email_funcionario));
CREATE UNIQUE INDEX IF NOT EXISTS uq_administradores_cpf ON public.administradores (cpf_administrador);
CREATE UNIQUE INDEX IF NOT EXISTS uq_administradores_email_lower ON public.administradores (lower(email_administrador));
CREATE INDEX IF NOT EXISTS idx_gfm_maquina ON public.gerencia_funcionario_maquina (id_maquina);
CREATE INDEX IF NOT EXISTS idx_gfp_produto ON public.gerencia_funcionario_produto (id_produto);
CREATE INDEX IF NOT EXISTS idx_gam_maquina ON public.gerencia_administrador_maquina (id_maquina);
CREATE INDEX IF NOT EXISTS idx_gap_produto ON public.gerencia_administrador_produto (id_produto);
CREATE INDEX IF NOT EXISTS idx_gaf_funcionario ON public.gerencia_administrador_funcionario (id_funcionario);

ALTER TABLE public.funcionarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.administradores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maquinas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gerencia_funcionario_maquina ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gerencia_funcionario_produto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gerencia_administrador_maquina ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gerencia_administrador_produto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gerencia_administrador_funcionario ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public_read_funcionarios" ON public.funcionarios;
CREATE POLICY "public_read_funcionarios" ON public.funcionarios FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_funcionarios" ON public.funcionarios;
CREATE POLICY "public_insert_funcionarios" ON public.funcionarios FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_funcionarios" ON public.funcionarios;
CREATE POLICY "public_update_funcionarios" ON public.funcionarios FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_funcionarios" ON public.funcionarios;
CREATE POLICY "public_delete_funcionarios" ON public.funcionarios FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_administradores" ON public.administradores;
CREATE POLICY "public_read_administradores" ON public.administradores FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_administradores" ON public.administradores;
CREATE POLICY "public_insert_administradores" ON public.administradores FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_administradores" ON public.administradores;
CREATE POLICY "public_update_administradores" ON public.administradores FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_administradores" ON public.administradores;
CREATE POLICY "public_delete_administradores" ON public.administradores FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_maquinas" ON public.maquinas;
CREATE POLICY "public_read_maquinas" ON public.maquinas FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_maquinas" ON public.maquinas;
CREATE POLICY "public_insert_maquinas" ON public.maquinas FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_maquinas" ON public.maquinas;
CREATE POLICY "public_update_maquinas" ON public.maquinas FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_maquinas" ON public.maquinas;
CREATE POLICY "public_delete_maquinas" ON public.maquinas FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_produtos" ON public.produtos;
CREATE POLICY "public_read_produtos" ON public.produtos FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_produtos" ON public.produtos;
CREATE POLICY "public_insert_produtos" ON public.produtos FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_produtos" ON public.produtos;
CREATE POLICY "public_update_produtos" ON public.produtos FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_produtos" ON public.produtos;
CREATE POLICY "public_delete_produtos" ON public.produtos FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina;
CREATE POLICY "public_read_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina;
CREATE POLICY "public_insert_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina;
CREATE POLICY "public_update_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina;
CREATE POLICY "public_delete_gerencia_funcionario_maquina" ON public.gerencia_funcionario_maquina FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto;
CREATE POLICY "public_read_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto;
CREATE POLICY "public_insert_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto;
CREATE POLICY "public_update_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto;
CREATE POLICY "public_delete_gerencia_funcionario_produto" ON public.gerencia_funcionario_produto FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina;
CREATE POLICY "public_read_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina;
CREATE POLICY "public_insert_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina;
CREATE POLICY "public_update_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina;
CREATE POLICY "public_delete_gerencia_administrador_maquina" ON public.gerencia_administrador_maquina FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_gerencia_administrador_produto" ON public.gerencia_administrador_produto;
CREATE POLICY "public_read_gerencia_administrador_produto" ON public.gerencia_administrador_produto FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_gerencia_administrador_produto" ON public.gerencia_administrador_produto;
CREATE POLICY "public_insert_gerencia_administrador_produto" ON public.gerencia_administrador_produto FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_gerencia_administrador_produto" ON public.gerencia_administrador_produto;
CREATE POLICY "public_update_gerencia_administrador_produto" ON public.gerencia_administrador_produto FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_gerencia_administrador_produto" ON public.gerencia_administrador_produto;
CREATE POLICY "public_delete_gerencia_administrador_produto" ON public.gerencia_administrador_produto FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "public_read_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario;
CREATE POLICY "public_read_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "public_insert_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario;
CREATE POLICY "public_insert_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "public_update_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario;
CREATE POLICY "public_update_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "public_delete_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario;
CREATE POLICY "public_delete_gerencia_administrador_funcionario" ON public.gerencia_administrador_funcionario FOR DELETE TO anon, authenticated USING (true);
